---
title: "Text Classification with R"
author: "Kalle Myllymaa"
date: "23 July 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading data

```{r data, cache = TRUE}
library(keras)
imdb <- dataset_imdb(num_words = 10000)
train_data <- imdb$train$x
train_labels <- imdb$train$y
test_data <- imdb$test$x
test_labels <- imdb$test$y
```

## Taking a look into the data
Training data (similarily to test data) consists of rows of vectors filled with ids for words.

```{r describe}
str(train_data[[1]])
train_labels[[1]]
```

```{r maxium, include=FALSE}
max(sapply(train_data, max))
```

Ids can be translated to words using a list mapping ids to string-presentations. For better performance, only 10 000 most common words are used and rest replaced with question marks.

```{r example_review, echo=FALSE}
# Named list mapping words to an integer index.
word_index <- keras::dataset_imdb_word_index()  
reverse_word_index <- names(word_index)
names(reverse_word_index) <- word_index

# Decodes the review. Note that the indices are offset by 3 because 0, 1, and 
# 2 are reserved indices for "padding," "start of sequence," and "unknown."
decoded_review <- sapply(train_data[[1]], function(index) {
  word <- if (index >= 3) reverse_word_index[[as.character(index - 3)]]
  if (!is.null(word)) word else "?"
})
cat(decoded_review)
```